steps:
- name: 'salvian/docker-lineageos:latest'
  entrypoint: /bin/bash
  args: ['./init.sh']
  env:
  - LINEAGE_BRANCH=${_LINEAGE_BRANCH}
  - LINEAGE_LOCAL_MANIFEST_XML=${_LINEAGE_LOCAL_MANIFEST_XML}
- name: 'salvian/docker-lineageos:latest'
  entrypoint: /bin/bash
  args: ['./build.sh']
  env:
  - USE_CCACHE=0
  - CCACHE_COMPRESS=0
  - CLOUDSDK_CONTAINER_CLUSTER=node-example-cluster
  - CCACHE_DIR=/workspace/ccache
  - ANDROID_JACK_VM_ARGS=-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx3G
  - LINEAGE_DEVICE=${_LINEAGE_DEVICE}
- name: 'salvian/docker-lineageos:latest'
  entrypoint: /bin/bash
  args: ['./publish.sh']
  env:
  - LINEAGE_BRANCH=${_LINEAGE_BRANCH}
  - LINEAGE_DEVICE=${_LINEAGE_DEVICE}
  - BINTRAY_URL=${_BINTRAY_URL}
  - BINTRAY_USER=${_BINTRAY_USER}
  - BINTRAY_API_KEY=${_BINTRAY_API_KEY}
  - BUILD_VERSION=gcp-${REVISION_ID}
timeout: 3600s
